# RSM fits vs. PROPROC and CBM fits; #LOCK line numbers from now on 
# Windows proproc results must be saved to MRMCRuns directory prior to running this
rm(list = ls()) # mainRSM.R # freeze lines
library(RJafroc)
library(bbmle)
library(stats)
library(ggplot2)
library(binom)
library(doParallel)
library(foreach)
library("caTools")
require("mvtnorm")

source("lesionDistribution.R")
source("rsmFunctions.R")
source("PlotRsmPropCbm.R")
source("loadDataFile.R")
source("ProprocFits.R") # contains results of PROPROC fits run on Windows machine

pathName <- "~/Dropbox/OnlineBook/Ch24/"
# included datasets
fileNames <-  c("TONY", "VD", "FR", "FED", "JT", "MAG", "OPT", "PEN", "NICO",
                "RUS", "DOB1", "DOB2", "DOB3", "FZR")
fileName <- fileNames[fileNames == "DOB1"]
#for (fileName in fileNames) {
  cat("fileName = ", fileName,"\n")
  frocData <- loadDataFile(fileName, pathName)
  rocData <- DfFroc2HrRoc(frocData)
  I <- length(rocData$modalityID);J <- length(rocData$readerID)
  K <- dim(rocData$NL)[3];K2 <- dim(rocData$LL)[3];K1 <- K - K2
  nLesDistr <- lesionDistribution(frocData)
  mrmcFile <- paste0("MRMCRuns/", fileName, "_MRMC.lrc")
  if (!file.exists(mrmcFile)){
    SaveDataFile(rocData, mrmcFile, format = "MRMC")
  }
  # retrieve PROPROC parameters
  ret <- ProprocFits(paste0(fileName, "_MRMC")) # this contains values generated by Windows DBM-MRMC with PROPROC fitting selected
  c1 <- ret$c1;da <- ret$da;aucProproc <- c1*0;aucRsm <- c1*0;aucCBM <- c1*0
  S <- rep(NA, I*J);AucC <- rep(NA, I*J)
  s <- 1 # following line prints a header row
  cat("mu, lambdaP, nuP, c, da, alpha, muCbm, aucRsm, aucProproc, aucCbm, chisqr(p-value), df","\n")
  retFileName <- paste0("ANALYZED/RSM-PROPROC-CBM/", "saveRetRoc", fileName) # XZ change
  if (!file.exists(retFileName)){  # if (TRUE || !file.exists(retFileName)){  # to enter loop
    retSmRoc <- list()
    for (i in 1:I){
      for (j in 1:J){
        # Metz and Pan Journal of Mathematical Psychology 43, 1?33 (1999)
        rho2 <- -(1-c1[i,j]^2)/(1+c1[i,j]^2)
        corr <- diag(2)
        corr[lower.tri(corr)] <- rho2
        corr[upper.tri(corr)] <- rho2
        lower <- rep(-Inf,2)
        upper <- c(-da[i,j]/sqrt(2),0)
        mean <- rep(0,2)
        aucProproc[i,j] <- pnorm(da[i,j]/sqrt(2))+2*pmvnorm(lower, upper, mean, corr)  #Eqn. 36 Metz and Pan
        tempRoc <- FitRsmRoc(frocData, i, j) # fit to RSM
        mu <- as.numeric(tempRoc$mu$mu)
        lambdaP <- as.numeric(tempRoc$lambdaP$lambdaP)
        nuP <- as.numeric(tempRoc$nuP$nuP)
        aucRsm[i,j] <- tempRoc$AUC$AUC
        empOp <- UtilOperatingPoints(rocData, i, j, opChType = "ROC")
        fpf <- empOp$FPF; tpf <- empOp$TPF
        retCbm <- FitCbmRoc(rocData,i,j)  # fit to CBM
        retSmRoc[[s]] <- as.list(
          c(tempRoc,
            list(
              nLesDistr = nLesDistr, aucProp = aucProproc[i,j], 
              da = da[i, j], c1 = c1[i, j],
              alpha=retCbm$alpha, muCbm=retCbm$mu, aucCbm=retCbm$AUC)))
        s <- s + 1
      }
    }
    stop("safety stop...")  # comment this to write a new results file or overwrite an exitsting file.
    save(retSmRoc, file = retFileName)
  }else{
    load(retFileName)
    s <- 1
    for (i in 1:I){
      for (j in 1:J){
        mu <- as.numeric(retSmRoc[[s]]$mu$mu)
        lambdaP <- as.numeric(retSmRoc[[s]]$lambdaP$lambdaP)
        nuP <- as.numeric(retSmRoc[[s]]$nuP$nuP)
        nLesDistr <- retSmRoc[[s]]$nLesDistr
        aucRsm[i, j] <- retSmRoc[[s]]$AUC$AUC
        aucProproc[i, j] <- retSmRoc[[s]]$aucProp
        empOp <- UtilOperatingPoints(rocData, i, j, opChType = "ROC")
        fpf <- empOp$FPF; tpf <- empOp$TPF
        compPlot <- PlotRsmPropCbm(
          which(fileNames == fileName), mu, lambdaP, nuP, nLesDistr, c1[i, j], da[i, j],
          retSmRoc[[s]]$muCbm, retSmRoc[[s]]$alpha,
          fpf, tpf, i, j, K1, K2, c(1, length(fpf)))
        print(compPlot)
        cat(mu, lambdaP, nuP, c1[i,j], da[i,j],retSmRoc[[s]]$alpha, retSmRoc[[s]]$muCbm,
            aucRsm[i,j], aucProproc[i,j], retSmRoc[[s]]$aucCbm, retSmRoc[[s]]$gdnss$pVal, retSmRoc[[s]]$gdnss$df, "\n")
        s <- s + 1
      }
    }
  }
#}

