rm(list = ls()) # mainDatasetViewer.R 
library(RJafroc)

source("rsmFunctions.R")
source("Transforms.R")
source("optFunctions.R")
source("addArguments.R")
source("FitURSM.R")
source("PlotRsmProp.R")
source("RJafrocIncludes.R")
source("ProprocFits.R")

stop("fix or delete me")

pathName <- "/Users/Dev/book2/06 E Appendices/E23 Datasets/"
# included datasets
fileNames <-  c("TONY", "VD", "FR", "FED", "JT", "MAG", "OPT", "PEN", "NICO",
                "RUS", "DOB1", "DOB2", "DOB3", "FZR")
fileName <- fileNames[fileNames == "TONY"]
cat("fileName = ", fileName,"\n")
frocData <- loadDataFile(fileName, pathName)
rocData <- DfFroc2Roc(frocData)
I <- length(rocData$modalityID)
J <- length(rocData$readerID)
# ret <- StSignificanceTesting(frocData, fom = "AFROC", method = "DBMH");print(ret$ciAvgRdrEachTrtRRRC)
lesionNum <- frocData$lesionNum
nLesDistr <- table(lesionNum)
if (length(nLesDistr) == 1) {
  nLesDistr <- c(lesionNum[1], 1)
  dim(nLesDistr) <- c(1, 2)
}else{
  nLesDistr <- t(rbind(as.numeric(unlist(attr(nLesDistr, "dimnames"))), as.vector(nLesDistr)))
}

mrmcFile <- paste0(pathName,"/MRMCRuns/", fileName, "_MRMC.lrc")
if (!file.exists(mrmcFile)){
  SaveDataFile(rocData, mrmcFile, format = "MRMC")
}
ret <- ProprocFits(fileName, pathName) # this contains values generated by Windows DBM-MRMC with PROPROC fitting selected
c1 <- ret$c1;da <- ret$da#; cat(c1, da,"\n");stop("temp")
aucProproc <- c1*0 # for ease of dimensioning 
aucURSM <- aucProproc
S <- rep(NA, I*J);AucC <- rep(NA, I*J)
s <- 1
cat("i, j, mu, lambdaP, nuP, aucURSM[i,j],aucProproc[i,j], S[s], AucC[s]", "\n")
retFileName <- paste0(pathName, "ANALYZED/URSM/", "saveRetRoc", fileName)
if (!file.exists(retFileName)){
  retSmRoc <- list()
  for (i in 1:I){
    for (j in 1:J){
      # Metz and Pan Journal of Mathematical Psychology 43, 1?33 (1999)
      rho2 <- -(1-c1[i,j]^2)/(1+c1[i,j]^2)
      corr <- diag(2)
      corr[lower.tri(corr)] <- rho2
      corr[upper.tri(corr)] <- rho2
      lower <- rep(-Inf,2)
      upper <- c(-da[i,j]/sqrt(2),0)
      mean <- rep(0,2)
      aucProproc[i,j] <- pnorm(da[i,j]/sqrt(2))+2*pmvnorm(lower, upper, mean, corr)  #Eqn. 36 Metz and Pan
      # tempRoc <- FitURSM(rocData, i, j, nLesDistr)
      tempRoc <- FitRsmRoc(frocData, i, j)
      mu <- as.numeric(tempRoc$mu$mu)
      lambdaP <- as.numeric(tempRoc$lambdaP$lambdaP)
      nuP <- as.numeric(tempRoc$nuP$nuP)
      aucURSM[i,j] <- PlotRsmOperatingCharacteristics(mu = mu, lambda = lambdaP * mu, nu = -log(1 - nuP)/mu, 
                                                      lesionDistribution = nLesDistr, type = "ROC")$aucROC
      empOp <- GetOperatingPoints(rocData, i, j, opChType = "ROC")
      fpf <- empOp$FPF; tpf <- empOp$TPF
      compPlot <- PlotRsmProp(mu, lambdaP, nuP, nLesDistr, c1[i, j], da[i, j], fpf, tpf, i, j)
      print(compPlot)
      S[s] <- nuP * exp(-lambdaP)
      AucC[s] <- pnorm(mu/sqrt(2))
      cat(i, j, mu, lambdaP, nuP, aucURSM[i,j],aucProproc[i,j], S[s], AucC[s], "\n")
      retSmRoc[[s]] <- as.list(c(tempRoc,
                                 list(nLesDistr = nLesDistr, aucProp = aucProproc[i,j], da = da[i, j], c1 = c1[i, j])))
      s <- s + 1
    }
  }
  save(retSmRoc, file = retFileName)
}else{
  load(retFileName)
  s <- 1
  for (i in 1:I){
    for (j in 1:J){
      mu <- as.numeric(retSmRoc[[s]]$mu$mu)
      lambdaP <- as.numeric(retSmRoc[[s]]$lambdaP$lambdaP)
      nuP <- as.numeric(retSmRoc[[s]]$nuP$nuP)
      nLesDistr <- retSmRoc[[s]]$nLesDistr
      aucURSM[i, j] <- PlotRsmOperatingCharacteristics(mu = mu, lambda = lambdaP * mu, nu = -log(1 - nuP)/mu, 
                                                 lesionDistribution = nLesDistr, type = "ROC")$aucROC
      aucProproc[i, j] <- retSmRoc[[s]]$aucProp
      empOp <- GetOperatingPoints(rocData, i, j, opChType = "ROC")
      fpf <- empOp$FPF; tpf <- empOp$TPF
      compPlot <- PlotRsmProp(mu, lambdaP, nuP, nLesDistr, c1[i, j], da[i, j], fpf, tpf, i, j)
      print(compPlot)
      S[s] <- nuP * exp(-lambdaP)
      AucC[s] <- pnorm(mu/sqrt(2))
      cat(i, j, mu, lambdaP, nuP, aucURSM[i, j], aucProproc[i, j], S[s], AucC[s], "\n")
      s <- s + 1
    }
  }
}


df <- data.frame(aucURSM = as.vector(aucURSM), aucProproc = as.vector(aucProproc))
p <- ggplot(data = df, aes(x = aucURSM, y = aucProproc)) + 
  geom_smooth(method = "lm", se = FALSE, color = "black", formula = y ~ 0 + x) +
  geom_point()
print(p)
m <- lm(aucProproc ~ 0 + aucURSM, df)
m <- lm(aucProproc ~ 0 + aucURSM, df);
cat("m = ", coef(m), ", R2 = ", summary(m)$r.squared, "\n")

df <- data.frame(S = S, AucC = AucC)
p <- ggplot(data = df, aes(x = S, y = AucC)) +
  geom_smooth(method = "lm", se = FALSE, color = "black", formula = y ~ x) +
  geom_point()
print(p)
m <- lm(AucC ~ S, df);
cat("a = ", coef(m)[1],", b = ", coef(m)[2],", r2 = ", summary(m)$r.squared,"\n")
